### ISSUE TITLE
Feature request : Show the energy prices in a dashboard

### ISSUE THREAD

**Issue by stauffenberg2020** [MattJeanes/TeslaMateAgile#54]
I was wondering if it would be somehow possible to display the instantaneous electricity price (at least for the current day) from Energinet/others in a dashboard. Because these values (from the last 7 days if I am not wrong) are available to TeslaMateAgile and if it can show the instantaneous price (at least for the current day) it would be great.

**Comment by MattJeanes** [comment]
It certainly can, check the [Optional Environment Variables](https://github.com/MattJeanes/TeslaMateAgile?tab=readme-ov-file#optional-environment-variables) section in the README for how to enable debug logging. Hopefully that'll tell you what you need.

**Comment by MattJeanes** [comment]
Not exactly no, there are two main problems that result in slightly inaccurate data. The first problem is that the Tesla does not provide detailed charging stats for each charging session via their API.

TeslaMate itself works around this by sampling the charger status frequently and adding up all that information at the end of a charge session to calculate the total energy used and energy added. It'll be close, but never exact. It also misses the very start of a charge too due to the polling so it will also miss that little bit too.

The second problem is that there is also minor electricity losses everywhere e.g. from your electricity meter/fuse box to the charger and then to the car lost as heat and the small induced electric field around the cables and for the power the charger itself uses too. This all means even that if Tesla did provide an exact measurement of the kWh received it would still be slightly out.

I also see the same problem for example with my home battery which measures all home power usage, it always records slightly less than we see on our bill / electricity meter and that does measure more accurately.

You may be able to compensate for these losses by setting the `TeslaMate__FeePerKilowattHour` (see README) but for most people they either don't notice or don't care about the small differences. Hope that helps!
