### ISSUE TITLE
Option for setting negative prices to 0 in Energinet

### ISSUE THREAD

**Issue by stauffenberg2020** [MattJeanes/TeslaMateAgile#60]
Hi @MattJeanes ,

I was wondering if you can make an option for setting the negative prices to `0` in the Energinet calculation part. 

For eg.
If the price from 10:00 to 11:00 is `-0.1` and `11 kw` is charged during this hour, 

The my calculations is like 
- Energinet__VAT
- Energinet__FixedPrices__Prices__0=00:00-24:00

=[`11 kw` * {max(`-0.1`, `0`) +  `Energinet__FixedPrices__Prices__0=00:00-24:00`}] * `Energinet__VAT`

**Comment by MattJeanes** [comment]
Hey, so if I understand correctly you just want the option so that the prices cannot be calculated as below zero and would clamp to zero instead?

Would this apply to the entire calculation including the fixed price or only to the raw data from energinet?

Also just so I can get a bit more of an understanding, why is it you want this option?

Thank you!

**Comment by MattJeanes** [comment]
Okay, I gotcha! Sounds like your use case could certainly apply to others as well then, and should be a relatively simple change.

I'll put this in for you hopefully sometime today but soon if not 😁

**Comment by MattJeanes** [comment]
Hey @stauffenberg2020, sorry - manic week! I've done this now in version [`v1.15.0`](https://github.com/MattJeanes/TeslaMateAgile/releases/tag/v1.15.0) if you'd like to try it out! 

The new configuration option is `Energinet__ClampNegativePrices=true/false`.

Let me know how it goes and I'll close the issue if you're happy.

**Comment by MattJeanes** [comment]
Fantastic! Glad it's all working 🙂 no problem at all
