### ISSUE TITLE
Tibber - System.Net.Http.HttpRequestException: Failed to call Tibber API: The first argument must be of type string... Received undefined

### ISSUE THREAD

**Issue by chuchynz** [MattJeanes/TeslaMateAgile#64]
Hi everyone. I am having an issue where it is failing to call the Tibber API with the following error while processing prices for different periods in the last few days or so.

`Failed to calculate charging cost / energy for charging process 4
System.Net.Http.HttpRequestException: Failed to call Tibber API: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
         at TeslaMateAgile.Services.TibberService.SendRequest(GraphQLHttpRequest request) in /src/TeslaMateAgile/Services/TibberService.cs:line 144
         at TeslaMateAgile.Services.TibberService.GetPriceData(DateTimeOffset from, DateTimeOffset to) in /src/TeslaMateAgile/Services/TibberService.cs:line 68
at TeslaMateAgile.PriceHelper.CalculateChargeCost(IEnumerable1 charges) in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 96
at TeslaMateAgile.PriceHelper.Update() in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 74
info: TeslaMateAgile.PriceHelper[0]`

This is the first time I have installed TeslaMateAgile and so far it has not been successful. I have tried on two different devices with the same result.

**Comment by MattJeanes** [comment]
"DEPRECATED - not particularly useful"

Thanks Tibber! Yes you're right, this appears to have broken the Tibber integration.

I've emailed Tibber's developer contact about this and will keep you posted.

Issue is pinned as others will definitely run into this. Thanks for letting me know.

**Comment by MattJeanes** [comment]
For the record, here is the email I sent to Tibber just now:

<details>
<summary>Email</summary>

> Subject: API Internal Server Error / Breaking Change
>
> Hello!
> 
> I maintain an application called TeslaMateAgile (https://github.com/MattJeanes/TeslaMateAgile) and in the past couple of days it seems that the PriceInfo range field no longer works and throws an internal server error.
> 
> I'm raising this on behalf of many Tibber customers who's integration using my application no longer works.
> 
> This is a sample query we are sending:
> ```
> {
>   viewer {
>     homes {
>       id
>       currentSubscription {
>         priceInfo {
>           range(
>             resolution: HOURLY
>             after: "MjAyNC0wOC0wN1QxODowOTozNS4wMDAwMDAwKzAwOjAw"
>             first: 2
>           ) {
>             nodes {
>               total
>               startsAt
>             }
>           }
>           current {
>             total
>             startsAt
>             level
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> And here is the response back we are seeing:
> 
> ```
> {
>   "errors": [
>     {
>       "message": "The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined",
>       "locations": [
>         {
>           "line": 7,
>           "column": 11
>         }
>       ],
>       "path": [
>         "viewer",
>         "homes",
>         0,
>         "currentSubscription",
>         "priceInfo",
>         "range"
>       ],
>       "extensions": {
>         "code": "INTERNAL_SERVER_ERROR",
>         "exception": {
>           "code": "ERR_INVALID_ARG_TYPE"
>         }
>       }
>     }
>   ],
>   "data": {
>     "viewer": {
>       "homes": [
>         {
>           "id": "96a14971-525a-4420-aae9-e5aedaa129ff",
>           "currentSubscription": {
>             "priceInfo": {
>               "range": null,
>               "current": {
>                 "total": 0.7498,
>                 "startsAt": "2024-10-07T16:00:00.000+02:00",
>                 "level": "EXPENSIVE"
>               }
>             }
>           }
>         }
>       ]
>     }
>   }
> }
> ```
>
> If we remove the priceInfo range field it no longer errors, but we very much need this information for my application to function. I've noticed on the developer API documentation it says this field is "DEPRECATED - not particularly useful" which I must disagree with, unless there is an alternative way to retrieve this information?
> 
> If you could let me know either way what's going on with this, whether it's intentional or accidental and what we can do about this?
> 
> Thank you very much,
> 
> Matt

</details>

**Comment by jstaro** [comment]
Hi, this was a bug that was introduced in the API between ~12:30 CEST and resolved at ~20:36 CEST yesterday. Sorry for any inconvenience that may have caused.

By the way, prices only update once a day (tomorrow's prices arrive at the earliest around 13:00 CEST, but fetching prices is very popular, so we have to spread out those requests over quite a long time, and cache the prices in the meantime, so if you are fine with checking after 14:00 CEST, you have a higher chance to get through on first attempt). If you query the `today`/`tomorrow` fields and stitch that together instead and cache the result on your end (if you cache it, you only need to fetch `tomorrow` and splice your local copy with that data), you will actually be calling the API in a more efficient manner than you are right now and you only need to do it once a day (modulo retries for network timeouts or "busting through" the cache).

Here are some tips: https://developer.tibber.com/docs/guides/calling-api#gql-client-reqs

There you can also read about a requirement to set a user-agent unique to your integration, so we can more easily contact you in case we need to get in touch about any upcoming API changes, or in case we see that you have a bug or otherwise misuse the API so we can help you out.

Best,
Jon@Tibber

**Comment by MattJeanes** [comment]
Hey @jstaro, thanks for responding so quickly - it is very much appreciated!

I'll make sure I get the user agent added in the next version for you 🙂

As for the `PriceInfo.range` field, we like to use this because TeslaMateAgile is stateless and stores no data itself. It works by looking at the charging start/stop times reported by the underlying TeslaMate project, and then we simply query the same (ish) time window from Tibber, allowing us to calculate the cost of a charge that happened at an arbitrary time, which could be at any point in history (although usually it is within the past day or so once it has caught up with old charges)

Using the "today" or "tomorrow" values could potentially results in missing data as we are more looking for historical data than forward looking data for this use case.

The Tibber integration is largely based on the Octopus Energy integration where they provide a very similar endpoint for their Agile tariff: https://developer.octopus.energy/rest/guides/endpoints#api-price-endpoints

What do you suggest we do if the `PriceInfo.range` field is not going to be around forever? We don't really want to have to handle caching / storing price information from yourselves or any other provider if possible.

**Comment by jstaro** [comment]
I see. Thanks for describing the use case! That use case is something that's worth remembering for whenever we get the time to make a new API, because this one is getting a bit long in the tooth.

It should be said though, as Grid Rewards and similar flex services/smart charging rewards become more popular, spot prices won't always show the whole picture in regards to charging cost, but it might be interesting still.

We will leave the `PriceInfo.range` field; the deprecation is mostly meant for new integrations not to start relying on it. Luckily there are very few integrations using this part of the schema, and it is a bit badly designed and hard-to-use (the various combinations of `before`, `after`, `first`, `last` can be hard to reason about, and some combinations don't even make sense).

The API was never meant to be used for stateless integrations, and many types of integrations are definitely a headache (not necessarily yours, because it fetches quite small ranges), especially during the time of the day when everyone wants to see tomorrow's prices. We'll see if we can cache this better somehow.

Thanks for the user-agent addition. It is definitely something that helps up finding out what kind of integrations are out there and their use cases so we can cater to as many needs as possible.

**Comment by MattJeanes** [comment]
@jstaro many thanks for the information and your feedback.

Indeed we are generally only fetching a few hours at most, and usually always a unique range rather than repeating the same range multiple times. I suppose across multiple different customers we could be fetching the same ranges though, but I don't know from my end that they will be the same values as I'm just calling with their API keys specific to their accounts. And of course these are all self-hosted by customers individually so I don't really have a way to share/cache that information across users even if I knew they would be the same values. In this light it does seem that caching from your end could potentially be useful indeed!

If things become a problem, please reach out to me on this project and we can work something out! I don't have any analytics inside my code, but from what I've seen in issues and requests etc the Tibber integration is quite popular indeed. You will probably be able to see better yourselves what kind of usage it has once people start upgrading to the next version with the user agent changes 😄 

Since things should be back working again now since the original bug was fixed, I'll go ahead and close this issue for now.

Again many thanks for the direct feedback on GitHub, definitely above and beyond what I was expecting 🙂

**Comment by MattJeanes** [comment]
Hey @jstaro, just a little heads up now that I've just released the version ([v1.16.0](https://github.com/MattJeanes/TeslaMateAgile/releases/tag/v1.16.0)) that sets the User-Agent string when talking to the Tibber API so hopefully you will start to see that as people upgrade 🙂
